# Generated by Django 3.1 on 2020-12-08 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peliculas',
            fields=[
                ('PeliculaId', models.AutoField(primary_key=True, serialize=False)),
                ('Titulo', models.CharField(max_length=200)),
                ('Director', models.CharField(max_length=200)),
                ('Anio', models.IntegerField(default=0)),
                ('Pais', models.CharField(max_length=50)),
                ('Duracion', models.IntegerField(default=0)),
                ('Sipnosis', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProgramacionSala',
            fields=[
                ('SalaId', models.AutoField(primary_key=True, serialize=False)),
                ('Numero', models.IntegerField(default=0)),
                ('Capacidad', models.IntegerField(default=0)),
                ('PeliculaId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sala.peliculas')),
            ],
        ),
    ]
