# Generated by Django 3.1 on 2020-12-10 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sala', '0002_auto_20201209_0528'),
    ]

    operations = [
        migrations.AddField(
            model_name='programacionsala',
            name='Disponible',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
