# Generated by Django 3.1 on 2020-12-10 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sala', '0004_auto_20201210_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programacionsala',
            name='PeliculaId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sala.peliculas', verbose_name='Pelicula'),
        ),
    ]
