# Generated by Django 2.1.2 on 2021-01-24 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sala', '0006_peliculas_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peliculas',
            name='Imagen',
            field=models.ImageField(default=0, null=True, upload_to='images/pelis'),
        ),
    ]
